# Generated by Django 4.0.3 on 2022-06-17 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ligas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('torneo', models.CharField(max_length=40)),
                ('equipos', models.IntegerField()),
                ('internacional', models.BooleanField()),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
