# Generated by Django 4.0.3 on 2022-06-17 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jugadores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('equipo', models.CharField(max_length=30)),
                ('fecha_nacimiento', models.DateField()),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
