# Generated by Django 4.0.3 on 2022-06-18 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jugadores', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jugadores',
            old_name='description',
            new_name='descripcion',
        ),
    ]
